/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jameslucino117 (https://sketchfab.com/jameslucino117)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rohitemsweaponsstaff-of-magnus-916d89a26a83494ab6f365485b244c89
Title: RoH>Items>Weapons>Staff of Magnus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function WeaponModel(props) {
  const { nodes, materials } = useGLTF("/weapon.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={2} rotation={[-0.2, 12, Math.PI /10]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StaffOfMagnus_Material005_0.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StaffOfMagnus_Material00007b_0.geometry}
            material={materials["Material.00007b"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/weapon.glb");
